### ISSUE TITLE
PrettyPrint type is not public

### ISSUE THREAD

**Issue by mitsuhiko** [mre/prettyprint#2]
The generated `PrettyPrint` types is not public in the crate.

**Comment by mre** [comment]
Using it like so in [cargo-inspect](https://github.com/mre/cargo-inspect/):
https://github.com/mre/cargo-inspect/blob/master/src/lib.rs#L48-L50

Isn't that enough to work with the crate? I mean, we can expose the `PrettyPrint` struct, but I'm not sure what would be your use-case for it? 🤔

**Comment by mre** [comment]
Related: https://github.com/sharkdp/bat/issues/423

**Comment by mitsuhiko** [comment]
Because it’s missing in the docs but also linked in the docs from `PrettyPrinter`.

**Comment by mitsuhiko** [comment]
Eg: a 404 here and an unlinked type as a return value from build: https://docs.rs/prettyprint/0.2.0/prettyprint/struct.PrettyPrinter.html

**Comment by mre** [comment]
Good point. 😅 That's auto-generated by [derive-builder](https://github.com/colin-kiegel/rust-derive-builder). We could add some custom documentation for the builder to fix that, I guess.

**Comment by mitsuhiko** [comment]
It also misses the docs then how to `print`. Is there a specific reason you don't want to just make the printer public? It's impossible to see from the docs how to use it.

**Comment by mre** [comment]
Apart from keeping the interface as small as possible to allow for internal refactoring without breaking usage, not really. Yeah, I think it's a good idea to make `PrettyPrint` public. Thanks for pointing that out. Would accept PRs for that. Otherwise I'll do it when I get to it.
