### ISSUE TITLE
prettyprint should have option for light terminal

### ISSUE THREAD

**Issue by TedDriggs** [mre/prettyprint#5]
On macOS, the default terminal is black text on a white background (and since I have difficulty seeing red-on-black, I prefer to keep it that way). As a result, when `cargo-expand` uses `prettyprint`, certain syntax elements become invisible white-on-white text that renders the output unusable.

![screen shot 2019-01-24 at 8 32 08 am](https://user-images.githubusercontent.com/4805575/51692816-8fe06b80-1fb2-11e9-8c1e-8c94ec999bb5.png)

# Options
1. Somehow detect the terminal background color and choose a contrasting color for primary text. Doing this in a cross-platform way might be difficult.
2. Add an option for callers to tell `prettyprint` to use a light theme vs a dark theme. This would require `cargo-expand` and others to expose a command-line flag of their own to choose light vs dark, but it would avoid reading anything from the terminal.

**Comment by mre** [comment]
This can be done already. Prettyprint supports all colorschemes that syntect supports. So it might be as easy as sending a pull request to cargo-expand (or cargo-inspect, which is also using prettyprint) and add the flag as well as choose a colorscheme.

**Comment by mre** [comment]
And yes I agree, the screenshot looks quite awful. :grinning:

**Comment by mre** [comment]
This is now done in [cargo-inspect](https://github.com/mre/cargo-inspect-vscode) thanks to @jonathansty.
See the release notes [here](https://github.com/mre/cargo-inspect/releases/tag/0.8.0).
It uses prettyprint 0.4.0, which has support for the `get_themes` method. See [here](https://docs.rs/prettyprint/0.4.0/prettyprint/struct.PrettyPrint.html).

I think we can close this. 🎉

**Comment by mre** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/175809/52271561-48f45d80-2944-11e9-8004-018592d1f43a.png">
